services:
  - type: web
    name: yt-summarizer
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.17
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py

    healthCheckPath: /
    autoDeploy: true

    disk:
      name: tmp-downloads
      mountPath: /tmp
      sizeGB: 1