services:
  - type: web
    name: yt-summarizer
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.17
      - key: PORT
        value: 5000

    healthCheckPath: /
    autoDeploy: true
    plan: free

    scalingConfig:
      maxInstances: 1

    additionalEnvVars:
      - key: DEBUG
        value: "False"
      - key: FLASK_ENV
        value: production