services:
  - type: web
    name: yt-summarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false