services:
  - type: web
    name: yt-summarizer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
      yt-dlp -U
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.17
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py

    healthCheckPath: /
    autoDeploy: true

    disk:
      name: tmp-downloads
      mountPath: /tmp
      sizeGB: 1